language: cpp
dist: xenial

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2
  - ctest -V

before_install:
  - eval "${MATRIX_EVAL}"

matrix:
  include:

    ######## LINUX CLANG ########
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    ######## LINUX GCC ########
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_script:
        - brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_script:
        - brew install llvm@4 && brew link --overwrite llvm@4 --force
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
      before_script:
        - brew install llvm@5 && brew link --overwrite llvm@5 --force
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++"
      before_script:
        - brew install llvm@6 && brew link --overwrite llvm@6 --force
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++"
      before_script:
        - brew install llvm@7 && brew link --overwrite llvm@7 --force
        - export PATH="/usr/local/opt/llvm/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/llvm/lib"
        - export CPPFLAGS="-I/usr/local/opt/llvm/include"

    ######## OSX GCC ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_script:
        - brew install gcc@4.9
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_script:
        - brew install gcc@5
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_script:
        - brew install gcc@6
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - brew install gcc@7
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      before_script:
        - brew link gcc@8

    # SONARCLOUD
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
        sonarcloud:
          organization: "zialus-github"
          token:
            secure: "l+4Wwj9uCrNvTyE2ZK3QYXRhoIsWaQ7hXzekI4rwV0Qiw6i5B1/rQlCyjHVx4VoCR2yKNu3f0I5j4f1CMrPURNxmDGueBEdVYpEMJF02Ys72GHB1RA6oQnB9SzqDnjznhokaJcCG3dg8YAv/jU0plJOKOg/HjzP70E6Lm0HechdgWYnWjzAPFyF3lrDqvltWE4aaGo+14m9UsiwgKUJgWD8rXJVe38TRZDv/1/TnWi846fqh7swqZ+1byK2tBH2uSh9+QZOkWNcRlVyQY/CnJrbQ+v99QKdP068RbhWaBX42IsZjHw6uSifrIvsa1OhmvvMlD7bDmmG/vMn5xqBOTMz9b7nWA1jWkoz3o2zCSJEBPzNfbwuiFzRrfzEqZURVlsx7dVzy6fqMGKOc/f5d+OSA3aks7kCzhlqWIVYfJOzwz5QpTRONjZhkj4dK28MfeDdVTMOJFKvLdX0GPtCra72LHKYR/rdRxXqaaFrxiSE5RMgkAGwBvadn2eslJ6ogY1jrgvR7UYKmeP5CBhVsIld1ARBAr5RB6gT4PXM1W+BGnyXDupNCAGu7IEOV12OixEv3nlUFdDrsW9gF+PtGRaq9G/tBmM1JZWYXTbFYn/3jXkMcIIxYfB7zaV2JKZ3J0baJtT4QBK9Y0eNJXQ9niI2XiH1/qdez0vMZ95Fd0wU="
      script:
        - git fetch --unshallow
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
        - ctest -V -C Release
        - cd ..
        - sonar-scanner
      env:
        - SONAR_CLOUD="YUP"
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # COVERITY_SCAN
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 # Max version supported by coverity scan right now
        coverity_scan:
          project:
            name: "Zialus/C-C0Compiler"
          notification_email: raulmendesferreira@gmail.com
          build_command_prepend: "git fetch --unshallow && cov-configure --comptype gcc --compiler gcc-7 --template && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .."
          build_command: "make"
          branch_pattern: master
      script:
        - echo "Coverity Scan"
      env:
        - secure: "XfGqM8sQu9DgimjAQUzUMFu3Xlu6/WSQNquIwslTI5mLGKi+9w2OpMvvTdhMz4dj0HAyY1G6OzzNKh5ZlQ6a2vQNRPwkWuxiFolEzqqP2t116cQnDh35MjCIohNT29224dBmzAxuKClP3iUBafTKhw1yN+zD6R3yfTfow7T3PUqc1eYG28EnXIHMs+Bg7WR/n5L5clfthds5pzsF473A9Tl/EkPRW9gEJatmRok0Tbxf1KLZ45nkLVEZqGuuOE+WJJYrfcEaRdHBFCQegxFJ9H9lhxalLizq5Q/Q7gZ4zjb/kGBJUSxxQduP9ntOy62AjcnnDgrhhSVoWmaHUeidjck/GtD5yXiaKjWJGcI5/hoEv8Mjri5jdMKglJB51RtAyLhKgQKgjZUqvXCN383SybvAYzfiazLfMG4iaKU3I3P2KGUPxLQFn2CBdr47dOB1AIYsi+k0FAb/yJNX+9Hpz0ZpeyEr/1UWsEUrtL954JkiKqzYVu7TuQtcUXsUbACibHlDUhP3z3kOYGHbSmGKhFuYVzhACGTyQIf5vGSHvFPwm+ne8u/Lc4eae9HirBqIpEdkLLY7nTUhsQzCunfOgBwfPe0Mx1oLUelsnd2d5PRmlLTC+tOLG6U8u8DfkoH/iLSgosK+9orY71IOW4u4xrUdz9xU3xJY+AxmtjqCdaw="
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
