language: cpp
dist: trusty
sudo: required


script:
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=Release ..
    - make
    - ctest -V

before_install:
    - eval "${MATRIX_EVAL}"

matrix:
  include:

    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_script:
        - brew update && brew cask uninstall oclint
        - brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_script:
        - brew update && brew cask uninstall oclint
        - brew install llvm@4 && brew link --overwrite llvm@4 --force
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
      before_script:
        - brew update && brew cask uninstall oclint
        - brew install llvm && brew link --overwrite llvm --force

    ######## OSX GCC ########
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_script:
        - brew update && brew cask uninstall oclint
        - brew install gcc@4.9
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_script:
        - brew update && brew cask uninstall oclint
        - brew install gcc@5
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_script:
        - brew update && brew cask uninstall oclint
        - brew install gcc@6
    - os: osx
      osx_image: xcode9.1
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - brew update && brew cask uninstall oclint
        - brew install gcc

    ######## LINUX CLANG ########
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-6-dev
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    ######## LINUX GCC ########
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # SONARCLOUD
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
        sonarcloud:
          organization: "zialus-github"
          token:
            secure: "l+4Wwj9uCrNvTyE2ZK3QYXRhoIsWaQ7hXzekI4rwV0Qiw6i5B1/rQlCyjHVx4VoCR2yKNu3f0I5j4f1CMrPURNxmDGueBEdVYpEMJF02Ys72GHB1RA6oQnB9SzqDnjznhokaJcCG3dg8YAv/jU0plJOKOg/HjzP70E6Lm0HechdgWYnWjzAPFyF3lrDqvltWE4aaGo+14m9UsiwgKUJgWD8rXJVe38TRZDv/1/TnWi846fqh7swqZ+1byK2tBH2uSh9+QZOkWNcRlVyQY/CnJrbQ+v99QKdP068RbhWaBX42IsZjHw6uSifrIvsa1OhmvvMlD7bDmmG/vMn5xqBOTMz9b7nWA1jWkoz3o2zCSJEBPzNfbwuiFzRrfzEqZURVlsx7dVzy6fqMGKOc/f5d+OSA3aks7kCzhlqWIVYfJOzwz5QpTRONjZhkj4dK28MfeDdVTMOJFKvLdX0GPtCra72LHKYR/rdRxXqaaFrxiSE5RMgkAGwBvadn2eslJ6ogY1jrgvR7UYKmeP5CBhVsIld1ARBAr5RB6gT4PXM1W+BGnyXDupNCAGu7IEOV12OixEv3nlUFdDrsW9gF+PtGRaq9G/tBmM1JZWYXTbFYn/3jXkMcIIxYfB7zaV2JKZ3J0baJtT4QBK9Y0eNJXQ9niI2XiH1/qdez0vMZ95Fd0wU="
      script:
        - mkdir build
        - cd build
        - cmake -D CMAKE_BUILD_TYPE=Release ..
        - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
        - ctest -V
        - cd ..
        - sonar-scanner

      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    # COVERITY_SCAN
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
        coverity_scan:
          project:
            name: "Zialus/C-C0Compiler"
            description: "C0 Compiler"
          notification_email: raulmendesferreira@gmail.com
          build_command_prepend: "mkdir build && cd build && cmake -D CMAKE_BUILD_TYPE=Release .."
          build_command: "make"
          branch_pattern: coverity_scan
      before_install:
        - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - secure: "HASmAsDPiOHN89ZtJiqrhL5dPtC7yRdU+ThVanCdGRsspt/z4gE0tC+tZ4OakoBiCOqB0y0RM6tXCqxJ3hvgHr/yMG07Qsh0gf3tAZycgL3BJ1AhXwyd7ySDU83UMyDFTWeFRBX96AHcDe0pCnNEviLEpz9Seb7HmnjwqGpEdr4JPjWDT670WUyqDWfBFDZkV1l3rYr7mgT8bzgTU9kH7kfR8YoigSZxN4OP4W/tbD3+jLnUMLvGTKfiuuP3mrZJHOgejrHKQZTKxGHKJyQFsmOSCL3RtMUaN+HI4X7bt+YZgMglmqX6l6iogNle1bJuobwnXlnvEZMBVNgMVYDYbmCISm2kRxsxbygMJZI8Vj9qNNFr8SqLJpfyyBsqNqoSST9ymFlUz6xM73BSTG3YiB4FdX1IghtGE46eaQ9sjm7rqjzGIxZ3urzKvHdcjK5jKZJpIO0zDrGYixtz9JabVrHlkfXciySa8xa3wQ18RY5WZS2kX7LTyF/G0uhdxwsfzHbRa+KSD46wzX3V77SjkuOBBclV5Yshagq9HA2eefepeQQXkauyP069Hv2Lk5TAgOwllcmLnhDsl6HWvFJAs6oH8Pm2TxM3UkAUvS/1Ij5QXXhrxoKCuV4kpPdGUTPgSAqbDmJ+Nuv/r4e2xvnG1ZBI2CZJJ+LqB8o8zhc05NA="
